[Mysql_Info]
api=http://czqacrm.c-zentrix.com/CZCRM/auto_assignment_api.php?
centralDb=czcrm_generic
clientDb=crm_manager

[mysql_primary_write]
mysqlHost=172.16.3.223
mysqlUser=root
mysqlPasswd=czentrix

[mysql_secodary_write]
mysqlHost=10.30.1.28
mysqlUser=ticketing
mysqlPasswd=czentrix

[mysql_primary_read]
mysqlHost=172.16.3.223
mysqlUser=root
mysqlPasswd=czentrix

[mysql_secodary_read]
mysqlHost=10.30.1.28
mysqlUser=ticketing
mysqlPasswd=czentrix

[_all_old___last_mysql_secodary_last]
mysqlHost=10.30.1.28
mysqlUser=ticketing
mysqlPasswd=czentrix

[_all_old___last_mysql_primary_last]
mysqlHost=10.128.0.49
mysqlUser=ticketing
mysqlPasswd=czentrix
