[loggers]
keys=root,main,queueRenewer,DeptMngr,clientMngr

[handlers]
keys=fileHandler

[formatters]
keys=fileFormatter

[logger_root]
handlers=fileHandler

[logger_main]
level=INFO
handlers=fileHandler
qualname=main
propagate=0

[logger_queueRenewer]
level=INFO
handlers=fileHandler
qualname=queueRenewer
propagate=0

[logger_DeptMngr]
level=INFO
handlers=fileHandler
qualname=DeptMngr
propagate=0

[logger_clientMngr]
level=INFO
handlers=fileHandler
qualname=DeptMngr
propagate=0

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=fileFormatter
args=('/var/log/czentrix/leadAssignLogs.txt',)

[formatter_fileFormatter]
format=[ %(lineno)s ] - %(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=
